activemq:
  ctx:
    initialContextFactory: org.wildfly.naming.client.WildFlyInitialContextFactory
    provideUrl: http-remoting://127.0.0.1:8080
    securityCredentials: admin1234
    securityPrincipal: jmsuser
  jndi:
    connectionFactory: jms/RemoteConnectionFactory
    queueEventLog: queue/ilds/eventLog
    queueInboundDispatch: queue/ilds/inbound/inboundDispatch
    queueOutboundDispatch: queue/ilds/outbound/outboundDispatch
    queueQuarantine: queue/ilds/quarantine

inbound:
  hostingSystemInfo:
    path: file:/etc/ilds/configuration/hosting-system-info.json

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ildsdb
    username: root

outbound:
  flow:
    concurrentConsumers: 20
    maxConcurrentConsumers: 20
    maxMessagesPerTask: 10
    jsch:
      config:
        "kex": "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256"
        "server_host_key": "ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256"
        "cipher.s2c": "aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"
        "cipher.c2s": "aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"
        "mac.s2c": "hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1"
        "mac.c2s": "hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1"
        "PubkeyAcceptedAlgorithms": "ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256"


retry:
  initialInterval: 3000
  multiplier: 2.0
  maxInterval: 20000

logging:
  file:
    name: logs/ilds_agent.log
  level:
    root: info
